import type { Product } from "./types";

const u = (id: string) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1400&q=75`;

export const products: Product[] = [
  {
    id: "p-001",
    slug: "sony-alpha-a7-iv-body",
    name: "Sony Alpha a7 IV Mirrorless Camera (Body Only)",
    sku: "SONY-A7IV-BODY",
    description:
      "The Sony a7 IV does double duty with strong stills and video performance. An advanced hybrid mirrorless camera, it pairs the resolution and autofocus photographers expect with robust 4K 60p recording for filmmakers and content creators.",
    highlights: [
      "33MP full-frame Exmor R CMOS sensor",
      "Up to 10 fps shooting, ISO 100–51200",
      "4K 60p video in 10-bit S-Cinetone",
      "3.68m-dot EVF with 120 fps refresh rate",
      '3" 1.03m-dot vari-angle touchscreen LCD',
    ],
    price: 1450000,
    images: [u("1502920917128-1aa500764cbd"), u("1516035069371-29a1b244cc32"), u("1519183071298-a2962feb14f4")],
    categoryId: "photography",
    stock: 4,
    isFeatured: true,
    isNew: false,
    status: "in_stock",
    createdAt: "2026-05-02",
  },
  {
    id: "p-002",
    slug: "prostudio-x1-condenser-microphone",
    name: "ProStudio X1 Condenser Microphone",
    sku: "PSX-1-COND",
    description:
      "Capture broadcast-quality sound with our flagship condenser mic. Purpose-built for podcasts, vocal tracking and voiceover work, it ships with a shock mount and pop filter so you can record cleanly from day one.",
    highlights: [
      "Large-diaphragm cardioid capsule",
      "20Hz–20kHz frequency response",
      "Includes shock mount and pop filter",
      "XLR output with low self-noise",
    ],
    price: 150000,
    images: [u("1590602847861-f357a9332bbc"), u("1545454675-3531b543be5d")],
    categoryId: "photography",
    stock: 12,
    isFeatured: true,
    isNew: true,
    status: "in_stock",
    createdAt: "2026-07-28",
  },
  {
    id: "p-003",
    slug: "aura-smartwatch-series-5",
    name: "Aura SmartWatch Series 5",
    sku: "AURA-SW5",
    description:
      "A premium smartwatch with an always-on AMOLED display, multi-day battery life and full health tracking. Pairs with Android and iOS, and handles calls straight from your wrist.",
    highlights: [
      '1.43" always-on AMOLED display',
      "Heart rate, SpO2 and sleep tracking",
      "Up to 7 days battery life",
      "5 ATM water resistance",
    ],
    price: 113400,
    compareAtPrice: 126000,
    images: [u("1523275335684-37898b6baf30"), u("1434493789847-2f02dc6ca35d")],
    categoryId: "wearables",
    stock: 20,
    isFeatured: true,
    isNew: false,
    status: "in_stock",
    createdAt: "2026-06-14",
  },
  {
    id: "p-004",
    slug: "chefmaster-digital-air-fryer-5l",
    name: "ChefMaster Digital Air Fryer 5L",
    sku: "CM-AF-5L",
    description:
      "Fry, roast and bake with up to 85% less oil. The 5L basket comfortably feeds a family of four, and eight digital presets take the guesswork out of everyday cooking.",
    highlights: [
      "5L non-stick dishwasher-safe basket",
      "8 one-touch cooking presets",
      "80–200°C temperature range",
      "Auto shut-off and cool-touch handle",
    ],
    price: 78000,
    compareAtPrice: 91800,
    images: [u("1574269909862-7e1d70bb8078"), u("1556909114-f6e7ad7d3136")],
    categoryId: "home-kitchen",
    stock: 0,
    isFeatured: true,
    isNew: false,
    status: "pre_order",
    createdAt: "2026-04-19",
  },
  {
    id: "p-005",
    slug: "lumina-pro-60w-bicolor-led-panel",
    name: "Lumina Pro 60W Bi-Color LED Panel",
    sku: "LUM-P60-BC",
    description:
      "A dependable bi-color LED panel for interviews, product shots and small studio sets. Adjust colour temperature from warm to daylight without gels, and dim smoothly to 0% with no flicker on camera.",
    highlights: [
      "60W output, CRI 96+",
      "3200K–5600K bi-color control",
      "0–100% flicker-free dimming",
      "Includes barn doors and light stand",
    ],
    price: 51000,
    images: [u("1558618666-fcd25c85cd64"), u("1601506521937-0121a7fc2a6b")],
    categoryId: "lighting",
    stock: 9,
    isFeatured: true,
    isNew: false,
    status: "in_stock",
    createdAt: "2026-06-30",
  },
  {
    id: "p-006",
    slug: "sonicmax-anc-wireless-headphones",
    name: "SonicMax ANC Wireless Headphones",
    sku: "SMX-ANC-01",
    description:
      "Hybrid active noise cancellation with 40mm drivers tuned for balanced, fatigue-free listening. Thirty hours of playback per charge, and a ten-minute top-up buys you five more hours.",
    highlights: [
      "Hybrid ANC with transparency mode",
      "40mm dynamic drivers",
      "30-hour battery, USB-C fast charge",
      "Bluetooth 5.3 with multipoint pairing",
    ],
    price: 119700,
    images: [u("1618366712010-f4ae9c647dcb"), u("1583394838336-acd977736f90")],
    categoryId: "electronics",
    stock: 15,
    isFeatured: true,
    isNew: false,
    status: "in_stock",
    createdAt: "2026-07-11",
  },
  {
    id: "p-007",
    slug: "canon-rf-24-70mm-f28-lens",
    name: "Canon RF 24-70mm f/2.8L IS USM Lens",
    sku: "CAN-RF2470",
    description:
      "The workhorse zoom for RF-mount bodies. A constant f/2.8 aperture across the range and five stops of image stabilisation make it equally at home at events, in the studio and on location.",
    highlights: [
      "Constant f/2.8 maximum aperture",
      "5-stop optical image stabilisation",
      "Nano USM autofocus motor",
      "Weather-sealed L-series build",
    ],
    price: 1620000,
    images: [u("1519183071298-a2962feb14f4"), u("1516035069371-29a1b244cc32")],
    categoryId: "photography",
    stock: 2,
    isFeatured: false,
    isNew: false,
    status: "in_stock",
    createdAt: "2026-03-22",
  },
  {
    id: "p-008",
    slug: "vortex-blend-1200w-blender",
    name: "Vortex Blend 1200W Countertop Blender",
    sku: "VTX-BL1200",
    description:
      "A 1200W motor and six-point stainless steel blade handle frozen fruit, nuts and hot soups without complaint. The 1.8L Tritan jug is shatter-resistant and dishwasher safe.",
    highlights: [
      "1200W copper motor",
      "1.8L BPA-free Tritan jug",
      "6-point stainless steel blade",
      "Pulse and 3 speed settings",
    ],
    price: 64500,
    images: [u("1585515320310-259814833e62"), u("1570222094114-d054a817e56b")],
    categoryId: "home-kitchen",
    stock: 18,
    isFeatured: false,
    isNew: true,
    status: "in_stock",
    createdAt: "2026-08-01",
  },
  {
    id: "p-009",
    slug: "ironcore-adjustable-dumbbell-set",
    name: "IronCore Adjustable Dumbbell Set (2–24kg)",
    sku: "IC-ADJ-24",
    description:
      "Replaces fifteen pairs of dumbbells with one dial. Turn to select your weight, lift it out of the cradle, and get on with the set — ideal when floor space is tight.",
    highlights: [
      "2kg to 24kg per dumbbell",
      "Dial-a-weight selection",
      "Sold as a pair with cradles",
      "Knurled anti-slip handle",
    ],
    price: 285000,
    images: [u("1584735935682-2f2b69dff9d2"), u("1534438327276-14e5300c3a48")],
    categoryId: "fitness",
    stock: 6,
    isFeatured: true,
    isNew: false,
    status: "in_stock",
    createdAt: "2026-05-27",
  },
  {
    id: "p-010",
    slug: "carbon-travel-tripod-t3",
    name: "Carbon Travel Tripod T3",
    sku: "CTT-T3",
    description:
      "Carbon fibre legs keep this tripod at 1.2kg while still supporting 8kg of camera and lens. Folds to 38cm, so it fits inside most carry-on bags.",
    highlights: [
      "10-layer carbon fibre legs",
      "1.2kg weight, 8kg load capacity",
      "Folds to 38cm for travel",
      "Ball head with Arca-Swiss plate",
    ],
    price: 96000,
    compareAtPrice: 112000,
    images: [u("1526406915894-7bcd65f60845"), u("1516035069371-29a1b244cc32")],
    categoryId: "photography",
    stock: 11,
    isFeatured: false,
    isNew: false,
    status: "in_stock",
    createdAt: "2026-04-08",
  },
  {
    id: "p-011",
    slug: "pulse-fit-band-4",
    name: "PulseFit Band 4 Activity Tracker",
    sku: "PF-BAND4",
    description:
      "A lightweight tracker that stays out of the way. Continuous heart rate, sleep staging and fourteen workout modes, with a fortnight of battery between charges.",
    highlights: [
      "14-day battery life",
      "Continuous heart rate and sleep staging",
      "14 sport modes",
      "IP68 dust and water resistance",
    ],
    price: 38500,
    images: [u("1434493789847-2f02dc6ca35d"), u("1523275335684-37898b6baf30")],
    categoryId: "wearables",
    stock: 34,
    isFeatured: false,
    isNew: true,
    status: "in_stock",
    createdAt: "2026-07-30",
  },
  {
    id: "p-012",
    slug: "studio-softbox-lighting-kit",
    name: "Studio Softbox Lighting Kit (2-Light)",
    sku: "SB-KIT-2L",
    description:
      "Two 60x60cm softboxes with stands and daylight-balanced bulbs — a complete starting setup for portraits, product photography and talking-head video.",
    highlights: [
      "2 × 60x60cm softboxes",
      "5500K daylight-balanced bulbs",
      "Adjustable 2m light stands",
      "Includes carry bag",
    ],
    price: 72000,
    images: [u("1601506521937-0121a7fc2a6b"), u("1558618666-fcd25c85cd64")],
    categoryId: "lighting",
    stock: 8,
    isFeatured: false,
    isNew: false,
    status: "in_stock",
    createdAt: "2026-02-16",
  },
  {
    id: "p-013",
    slug: "keychron-k3-mechanical-keyboard",
    name: "Keychron K3 Low-Profile Mechanical Keyboard",
    sku: "KC-K3-LP",
    description:
      "A slim 75% mechanical keyboard that connects to three devices over Bluetooth or runs wired over USB-C. Hot-swappable switches let you change the feel without soldering.",
    highlights: [
      "75% low-profile layout",
      "Hot-swappable optical switches",
      "Bluetooth 5.1, 3-device pairing",
      "Mac and Windows keycaps included",
    ],
    price: 89000,
    images: [u("1587829741301-dc798b83add3"), u("1546435770-a3e426bf472b")],
    categoryId: "electronics",
    stock: 14,
    isFeatured: false,
    isNew: false,
    status: "in_stock",
    createdAt: "2026-06-05",
  },
  {
    id: "p-014",
    slug: "yoga-mat-pro-6mm",
    name: "YogaMat Pro 6mm Non-Slip Exercise Mat",
    sku: "YM-PRO-6",
    description:
      "A 6mm TPE mat with enough cushioning for floor work and enough grip to hold a pose when your hands are damp. Rolls up with the included strap.",
    highlights: [
      "6mm TPE cushioning",
      "Double-sided non-slip texture",
      "183 × 61cm surface",
      "Includes carry strap",
    ],
    price: 21500,
    images: [u("1591291621164-2c6367723315"), u("1571019613454-1cb2f99b2d8b")],
    categoryId: "fitness",
    stock: 42,
    isFeatured: false,
    isNew: false,
    status: "in_stock",
    createdAt: "2026-01-30",
  },
  {
    id: "p-015",
    slug: "espresso-master-15bar",
    name: "EspressoMaster 15-Bar Coffee Machine",
    sku: "EM-15BAR",
    description:
      "Pull proper espresso at home with a 15-bar pump, thermoblock heating and a steam wand for milk. Takes ground coffee or ESE pods.",
    highlights: [
      "15-bar Italian pump",
      "Professional steam wand",
      "1.5L removable water tank",
      "Ground coffee and ESE pod compatible",
    ],
    price: 168000,
    images: [u("1608354580875-30bd4168b351"), u("1570222094114-d054a817e56b")],
    categoryId: "home-kitchen",
    stock: 5,
    isFeatured: false,
    isNew: false,
    status: "in_stock",
    createdAt: "2026-03-11",
  },
  {
    id: "p-016",
    slug: "atlas-4k-action-camera",
    name: "Atlas 4K Action Camera with Stabilisation",
    sku: "ATL-4K-AC",
    description:
      "Waterproof to 10m without a housing, with electronic stabilisation that holds footage steady on a bike, a board or a handheld run. Two batteries and a mount kit in the box.",
    highlights: [
      "4K 60fps video capture",
      "EIS 3.0 electronic stabilisation",
      "Waterproof to 10m housing-free",
      "2 batteries and mounting kit included",
    ],
    price: 132000,
    compareAtPrice: 155000,
    images: [u("1526170375885-4d8ecf77b99f"), u("1502920917128-1aa500764cbd")],
    categoryId: "photography",
    stock: 0,
    isFeatured: false,
    isNew: false,
    status: "out_of_stock",
    createdAt: "2026-05-15",
  },
  {
    id: "p-017",
    slug: "soundwave-portable-speaker",
    name: "SoundWave Portable Bluetooth Speaker",
    sku: "SW-PORT-01",
    description:
      "A rugged 30W speaker that plays for twenty hours and shrugs off rain and dust. Pair two of them for genuine stereo separation.",
    highlights: [
      "30W stereo output",
      "20-hour playtime",
      "IPX7 waterproof rating",
      "True Wireless stereo pairing",
    ],
    price: 54000,
    images: [u("1608043152269-423dbba4e7e1"), u("1545454675-3531b543be5d")],
    categoryId: "electronics",
    stock: 22,
    isFeatured: false,
    isNew: false,
    status: "in_stock",
    createdAt: "2026-04-27",
  },
  {
    id: "p-018",
    slug: "resistance-band-set-pro",
    name: "Resistance Band Set Pro (5-Piece)",
    sku: "RB-SET-5",
    description:
      "Five latex bands from light to extra heavy, with door anchor, handles and ankle straps — a full-body setup that packs into a small bag.",
    highlights: [
      "5 resistance levels, 5–35kg",
      "Natural latex construction",
      "Door anchor and ankle straps",
      "Handles and carry bag included",
    ],
    price: 18000,
    images: [u("1584464491033-06628f3a6b7b"), u("1584735935682-2f2b69dff9d2")],
    categoryId: "fitness",
    stock: 50,
    isFeatured: false,
    isNew: true,
    status: "in_stock",
    createdAt: "2026-08-05",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getFeaturedProducts(limit = 4): Product[] {
  return products.filter((p) => p.isFeatured).slice(0, limit);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  const sameCategory = products.filter((p) => p.categoryId === product.categoryId && p.id !== product.id);
  if (sameCategory.length >= limit) return sameCategory.slice(0, limit);
  const fillers = products.filter((p) => p.categoryId !== product.categoryId && p.id !== product.id);
  return [...sameCategory, ...fillers].slice(0, limit);
}

export function countByCategory(categoryId: string): number {
  return products.filter((p) => p.categoryId === categoryId).length;
}
